spam_keywords = [
    "$$$",
    "100% free",
    "additional income",
    "be your own boss",
    "beneficiary",
    "best price",
    "billion",
    "cash",
    "cash bonus",
    "cents on the dollar",
    "cheap",
    "claims",
    "collect",
    "compare rates",
    "credit",
    "credit card",
    "debt",
    "discount",
    "double your income",
    "earn",
    "earn money",
    "extra cash",
    "fast cash",
    "financial freedom",
    "free",
    "free access",
    "free gift",
    "free trial",
    "hidden charges",
    "income",
    "investment",
    "invoice",
    "loan",
    "lowest price",
    "make money",
    "million",
    "money",
    "money back",
    "mortgage",
    "no fees",
    "no cost",
    "no hidden costs",
    "payment",
    "price",
    "profit",
    "quote",
    "refinance",
    "refund",
    "risk-free",
    "save big money",
    "subject to credit",
    "unsecured debt",
    "unsolicited",
    "work from home",

    # --- Urgency / Action-Oriented ---
    "act now",
    "apply now",
    "call now",
    "click here",
    "click below",
    "do it today",
    "don't delete",
    "expire",
    "for a limited time",
    "get it now",
    "hurry",
    "immediately",
    "instant",
    "limited time",
    "new customers only",
    "now",
    "offer expires",
    "once in a lifetime",
    "order now",
    "please read",
    "special promotion",
    "take action",
    "time sensitive",
    "urgent",
    "visit our website",
    "while supplies last",

    # --- Health / Medical / Adult ---
    "adipex",
    "ambien",
    "cialis",
    "diet",
    "enlargement",
    "levitra",
    "lose weight",
    "medicine",
    "online pharmacy",
    "pharmacy",
    "pills",
    "prescription",
    "reverses aging",
    "sexual",
    "valium",
    "viagra",
    "vicodin",
    "weight loss",
    "xanax",

    # --- Prizes / Winnings / Scams ---
    "amazing",
    "as seen on",
    "congratulations",
    "fantastic deal",
    "for you",
    "guaranteed",
    "lottery",
    "prize",
    "selected",
    "stop snoring",
    "winner",
    "winning",
    "won",
    "you have been selected",
    "you are a winner",

    # --- Marketing / General ---
    "ads",
    "auto email removal",
    "bulk email",
    "buy direct",
    "cancel at any time",
    "check or money order",
    "direct email",
    "direct marketing",
    "email marketing",
    "increase sales",
    "internet marketing",
    "marketing",
    "member",
    "multi-level marketing",
    "online marketing",
    "opt-in",
    "remove",
    "sale",
    "search engine listings",
    "subscribe",
    "unsubscribe",
    "web traffic",
    
    # --- Phishing / Security ---
    "access",
    "account",
    "confirm",
    "in accordance with laws",
    "login",
    "password",
    "secure",
    "security",
    "suspended",
    "update",
    "verify",
]

lstspam=[]
with open("mail.txt","r",encoding="utf-8") as f:
    for line in f:
        for keyword in spam_keywords:
            if keyword in line:
                lstspam.append(keyword)
                

if len(lstspam)>0:
    print("Spam")
    print(lstspam)
else:
    print("Ham ")
